import React from 'react';
import { connect } from 'react-redux';

import './css/TimelinePage.css';

import UserPost from './UserPost';

// This is UserPosts
class UserPosts extends React.Component {
    /* Receive the following parameters as prop:

    postCount - number of posts to generate, or if max. posts available exceeded then all the posts. This is also the default
    userName - an object representing posting user's posts
    */

    render() {
        // Determine the length of the posts array
        const postCountMax = this.props.posts.length;
        /*  Check if the this.props.postCount has been supplied. If it has, then use that as a potential maximum (another check still)
            performed below to make sure that we never exceed the number of elements in the this.props.posts array */
        const postCountTarget = (this.props.postCount === undefined || this.props.postCount === null) ? postCountMax : Math.min(this.props.postCount, postCountMax);

        // Construct an array that contains all the Li elements based on information passed to the component
        const retLi = [];
        for (let postNumber = 0; postNumber < postCountTarget; postNumber++) {
            const post = this.props.posts[postNumber];
            // Add key from a simple index to prevent warning at a later stage, create an array of <li> elements generated by userPost
            retLi.push(<UserPost key={postNumber} userInfo={this.props.profile} userPost={post} />)
        }

        // Deconstruct the array in order to display it. Thanks JSX
        return (
            <ul>
                {[...retLi]}
            </ul>
        );
    }
}


/*  Using the react-redux' connect function to retrieve the information from the Redux store 
    based on the value received by the component in one of it's props.
    Ref: https://react-redux.js.org/api/connect */

export default connect(
    (state, ownProps) => {
        /*  Prop 'user' is passed to the UserPosts component in order to retrieve user's information and posts
            from the Redux store */

        const user = ownProps.userName;
        
        const [userData] = state.map(userObject => {
            // Get the name of the current object's key, corresponding to username in the Redux store.
            const userIter = Object.keys(userObject).toString();
            // Check if the user found corresponds to the user we're looking for
            if (userIter === user) {
                /*  Deconstruct the object to extract the user profile into userProfile object and the
                    posts into the userPosts array */
                const { [userIter]: { profile: userProfile } } = userObject;
                const { [userIter]: { posts: userPosts } } = userObject;

                // Return an object containing the user information we're seeking.
                return { [userIter]: { profile: userProfile, posts: userPosts } };
            } else {
                /*  Since map function returns an array, we want to control what data type is in the 
                    array for non matching values, so that they can be easily removed by .filter method */
                return null;
            }
        }).filter(userObject => userObject !== null);

        // Simplify userData object to make it easy to manipulate
        const { [user]: { posts: userPosts } } = userData;
        const { [user]: { profile: userProfile } } = userData;

        // Add username key/prop to the userProfile object to cater for userPost component requirements
        const userProfileWithUsername = { ...userProfile, user: user };

        // Return objects as props to the Component
        return {
            posts: userPosts,
            profile: userProfileWithUsername
        };
    }
)(UserPosts);